# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialogButtonBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(702, 483)
        self.buttonbox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonbox.setGeometry(QtCore.QRect(150, 270, 271, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonbox.sizePolicy().hasHeightForWidth())
        self.buttonbox.setSizePolicy(sizePolicy)
        self.buttonbox.setMinimumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.buttonbox.setFont(font)
        self.buttonbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonbox.setAutoFillBackground(False)
        self.buttonbox.setStyleSheet("QPushButton{\n"
"    border-radius:8;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    min-width: 70px; max-width: 70px;\n"
"    min-height: 32px; max-height: 32px;\n"
"    font-family:微软雅黑;\n"
"    font-weight:500;\n"
"    font-size:17px\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:8;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    min-width: 70px; max-width: 70px;\n"
"    min-height: 32px; max-height: 32px;\n"
"    font-family:微软雅黑;\n"
"    font-weight:500;\n"
"    font-size:17px\n"
"}")
        self.buttonbox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonbox.setCenterButtons(True)
        self.buttonbox.setObjectName("buttonbox")
        self.info_content = QtWidgets.QLabel(Dialog)
        self.info_content.setGeometry(QtCore.QRect(111, 170, 350, 120))
        self.info_content.setMinimumSize(QtCore.QSize(350, 120))
        self.info_content.setStyleSheet("border:0px;\n"
"font-size:19px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);")
        self.info_content.setAlignment(QtCore.Qt.AlignCenter)
        self.info_content.setObjectName("info_content")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 130, 371, 231))
        self.label.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius:15px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.buttonbox.raise_()
        self.info_content.raise_()

        self.retranslateUi(Dialog)
        self.buttonbox.accepted.connect(Dialog.accept)
        self.buttonbox.rejected.connect(Dialog.reject)
        self.buttonbox.button(QDialogButtonBox.Ok).setText("打开")
        self.buttonbox.button(QDialogButtonBox.Cancel).setText("关闭")
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonbox.setToolTip(_translate("Dialog", "<html><head/><body><p/></body></html>"))
        self.info_content.setText(_translate("Dialog", "识别结束，结果保存在out/中"))
