# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(10, 0, 1101, 651))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("meter_reading_res/background_gray.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 30, 291, 591))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 51, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("meter_reading_res/log_blue.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 221, 51))
        self.label_3.setStyleSheet("font-size:22px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"color: rgb(74, 74, 74);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_picwin = QtWidgets.QPushButton(self.frame)
        self.btn_picwin.setGeometry(QtCore.QRect(50, 160, 191, 51))
        self.btn_picwin.setStyleSheet("QPushButton{\n"
"    border-radius:10;\n"
"    background-color: rgb(19, 34, 122);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:20px\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:10;\n"
"    background-color: rgb(30, 50, 122);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:20px\n"
"}")
        self.btn_picwin.setObjectName("btn_picwin")
        self.btn_videowin = QtWidgets.QPushButton(self.frame)
        self.btn_videowin.setGeometry(QtCore.QRect(50, 230, 191, 51))
        self.btn_videowin.setStyleSheet("QPushButton{\n"
"    border-radius:10;\n"
"    background-color: rgb(19, 34, 122);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:20px\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:10;\n"
"    background-color: rgb(30, 50, 122);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:20px\n"
"}")
        self.btn_videowin.setObjectName("btn_videowin")
        self.btn_run = QtWidgets.QPushButton(self.frame)
        self.btn_run.setGeometry(QtCore.QRect(50, 370, 191, 121))
        self.btn_run.setStyleSheet("QPushButton{\n"
"    border-radius:10;\n"
"    background-color: rgb(19, 34, 122);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:10;\n"
"    background-color: rgb(30, 50, 122);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_run.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("meter_reading_res/pause1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_run.setIcon(icon)
        self.btn_run.setIconSize(QtCore.QSize(60, 60))
        self.btn_run.setObjectName("btn_run")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 550, 102, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_setting = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_setting.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"}\n"
"")
        self.btn_setting.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("meter_reading_res/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon1)
        self.btn_setting.setObjectName("btn_setting")
        self.horizontalLayout.addWidget(self.btn_setting)
        self.btn_home = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_home.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"}\n"
"")
        self.btn_home.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("meter_reading_res/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon2)
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout.addWidget(self.btn_home)
        self.btn_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_exit.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"}\n"
"")
        self.btn_exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("meter_reading_res/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon3)
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.btn_camera = QtWidgets.QPushButton(self.frame)
        self.btn_camera.setGeometry(QtCore.QRect(50, 300, 191, 51))
        self.btn_camera.setStyleSheet("QPushButton{\n"
"    border-radius:10;\n"
"    background-color: rgb(19, 34, 122);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:20px\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:10;\n"
"    background-color: rgb(30, 50, 122);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:20px\n"
"}")
        self.btn_camera.setObjectName("btn_camera")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(330, 20, 751, 601))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 741, 591))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.filepath = QtWidgets.QLineEdit(self.frame_2)
        self.filepath.setGeometry(QtCore.QRect(30, 30, 681, 41))
        self.filepath.setStyleSheet("border: 2px solid;\n"
"border-color: rgb(19, 34, 122);\n"
"border-radius: 10px; \n"
"padding-left: 10px;\n"
"color: rgb(19, 34, 122);\n"
"")
        self.filepath.setText("")
        self.filepath.setObjectName("filepath")
        self.frame_show = QtWidgets.QLabel(self.frame_2)
        self.frame_show.setGeometry(QtCore.QRect(30, 200, 681, 371))
        self.frame_show.setStyleSheet("border: 1px solid;\n"
"border-radius:20px;\n"
"border-color: rgb(19, 34, 122);")
        self.frame_show.setText("")
        self.frame_show.setAlignment(QtCore.Qt.AlignCenter)
        self.frame_show.setObjectName("frame_show")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(31, 80, 91, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(19, 34, 122);\n"
"font-family:微软雅黑;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pic_0 = QtWidgets.QLabel(self.layoutWidget_2)
        self.pic_0.setStyleSheet("border: 1px solid;\n"
"border-radius:10px;\n"
"border-color: rgb(19, 34, 122);")
        self.pic_0.setText("")
        self.pic_0.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_0.setObjectName("pic_0")
        self.verticalLayout.addWidget(self.pic_0)
        self.verticalLayout.setStretch(1, 10)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(270, 80, 151, 101))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(19, 34, 122);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.pic_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.pic_2.setStyleSheet("border: 1px solid;\n"
"border-radius:10px;\n"
"border-color: rgb(19, 34, 122);")
        self.pic_2.setText("")
        self.pic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_2.setObjectName("pic_2")
        self.verticalLayout_3.addWidget(self.pic_2)
        self.verticalLayout_3.setStretch(1, 10)
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(450, 80, 151, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(19, 34, 122);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.pic_3 = QtWidgets.QLabel(self.layoutWidget_4)
        self.pic_3.setStyleSheet("border: 1px solid;\n"
"border-radius:10px;\n"
"border-color: rgb(19, 34, 122);")
        self.pic_3.setText("")
        self.pic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_3.setObjectName("pic_3")
        self.verticalLayout_4.addWidget(self.pic_3)
        self.verticalLayout_4.setStretch(1, 10)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(150, 80, 91, 101))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(19, 34, 122);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.pic_1 = QtWidgets.QLabel(self.layoutWidget_5)
        self.pic_1.setStyleSheet("border: 1px solid;\n"
"border-radius:10px;\n"
"border-color: rgb(19, 34, 122);")
        self.pic_1.setText("")
        self.pic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_1.setObjectName("pic_1")
        self.verticalLayout_2.addWidget(self.pic_1)
        self.verticalLayout_2.setStretch(1, 10)
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(630, 80, 81, 101))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(19, 34, 122);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.pic_result = QtWidgets.QLabel(self.layoutWidget_6)
        self.pic_result.setStyleSheet("border: 1px solid;\n"
"border-radius:10px;\n"
"border-color: rgb(19, 34, 122);")
        self.pic_result.setText("")
        self.pic_result.setAlignment(QtCore.Qt.AlignCenter)
        self.pic_result.setObjectName("pic_result")
        self.verticalLayout_5.addWidget(self.pic_result)
        self.verticalLayout_5.setStretch(1, 10)
        self.btn_right = QtWidgets.QPushButton(self.frame_2)
        self.btn_right.setGeometry(QtCore.QRect(670, 340, 31, 81))
        self.btn_right.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"border-radius:3px;\n"
"border : none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius:3px;\n"
"border : none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:3px;\n"
"border : none;\n"
"}")
        self.btn_right.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("meter_reading_res/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_right.setIcon(icon4)
        self.btn_right.setObjectName("btn_right")
        self.btn_left = QtWidgets.QPushButton(self.frame_2)
        self.btn_left.setGeometry(QtCore.QRect(40, 340, 31, 81))
        self.btn_left.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"border-radius:3px;\n"
"border : none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius:3px;\n"
"border : none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:3px;\n"
"border : none;\n"
"}")
        self.btn_left.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("meter_reading_res/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_left.setIcon(icon5)
        self.btn_left.setObjectName("btn_left")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 741, 591))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20\n"
"}\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.video_show = QtWidgets.QLabel(self.frame_3)
        self.video_show.setGeometry(QtCore.QRect(20, 20, 701, 351))
        self.video_show.setStyleSheet("border: 2px solid;\n"
"border-radius:0;\n"
"border-color: rgb(19, 34, 122);")
        self.video_show.setText("")
        self.video_show.setObjectName("video_show")
        self.groupbox = QtWidgets.QGroupBox(self.frame_3)
        self.groupbox.setGeometry(QtCore.QRect(380, 380, 341, 201))
        self.groupbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupbox.setStyleSheet("QGroupBox{\n"
"border: 2px solid;\n"
"border-radius:0;\n"
"bottom:19px;\n"
"font-size:14px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"border-color: rgb(19, 34, 122);\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"top:-4px;\n"
"left:100px;\n"
"color: rgb(19, 34, 122);\n"
"}")
        self.groupbox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupbox.setObjectName("groupbox")
        self.reslist = QtWidgets.QLabel(self.frame_3)
        self.reslist.setGeometry(QtCore.QRect(20, 380, 351, 201))
        self.reslist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reslist.setStyleSheet("border:2px solid;\n"
"border-radius:0px;\n"
"border-color: rgb(19, 34, 122);\n"
"font-size:20px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"")
        self.reslist.setFrameShape(QtWidgets.QFrame.Box)
        self.reslist.setText("")
        self.reslist.setAlignment(QtCore.Qt.AlignCenter)
        self.reslist.setObjectName("reslist")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_4 = QtWidgets.QFrame(self.page_3)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 741, 591))
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20\n"
"}\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.video_show_camera = QtWidgets.QLabel(self.frame_4)
        self.video_show_camera.setGeometry(QtCore.QRect(20, 20, 701, 351))
        self.video_show_camera.setStyleSheet("border: 2px solid;\n"
"border-radius:0;\n"
"border-color: rgb(19, 34, 122);")
        self.video_show_camera.setText("")
        self.video_show_camera.setObjectName("video_show_camera")
        self.groupbox_camera = QtWidgets.QGroupBox(self.frame_4)
        self.groupbox_camera.setGeometry(QtCore.QRect(380, 380, 341, 201))
        self.groupbox_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupbox_camera.setStyleSheet("QGroupBox{\n"
"border: 2px solid;\n"
"border-radius:0;\n"
"bottom:19px;\n"
"font-size:14px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"border-color: rgb(19, 34, 122);\n"
"}\n"
"\n"
"QGroupBox::title{\n"
"top:-4px;\n"
"left:100px;\n"
"color: rgb(19, 34, 122);\n"
"}")
        self.groupbox_camera.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupbox_camera.setObjectName("groupbox_camera")
        self.reslist_camera = QtWidgets.QLabel(self.frame_4)
        self.reslist_camera.setGeometry(QtCore.QRect(20, 380, 351, 201))
        self.reslist_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reslist_camera.setStyleSheet("border:2px solid;\n"
"border-radius:0px;\n"
"border-color: rgb(19, 34, 122);\n"
"font-size:20px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"")
        self.reslist_camera.setFrameShape(QtWidgets.QFrame.Box)
        self.reslist_camera.setText("")
        self.reslist_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.reslist_camera.setObjectName("reslist_camera")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "  指针式仪表智能读数"))
        self.btn_picwin.setText(_translate("MainWindow", "选择图片"))
        self.btn_videowin.setText(_translate("MainWindow", "选择视频"))
        self.btn_camera.setText(_translate("MainWindow", "打开摄像头"))
        self.label.setText(_translate("MainWindow", "原图"))
        self.label_5.setText(_translate("MainWindow", "圆环转矩形图"))
        self.label_6.setText(_translate("MainWindow", "刻度图"))
        self.label_4.setText(_translate("MainWindow", "分割图"))
        self.label_7.setText(_translate("MainWindow", "结果"))
        self.groupbox.setTitle(_translate("MainWindow", "读数随时间变换曲线"))
        self.groupbox_camera.setTitle(_translate("MainWindow", "读数随时间变换曲线"))
