# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settingui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 91, 21))
        self.label.setStyleSheet("font-size:16px;\n"
"font-weight:400;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.fenduzhi = QtWidgets.QLineEdit(self.centralwidget)
        self.fenduzhi.setGeometry(QtCore.QRect(50, 130, 211, 31))
        self.fenduzhi.setStyleSheet("font-size:15px;\n"
"font-weight:400;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);\n"
"border : none;\n"
"background-color: rgb(0, 0, 0);")
        self.fenduzhi.setObjectName("fenduzhi")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 240, 141, 21))
        self.label_2.setStyleSheet("font-size:16px;\n"
"font-weight:400;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.camera_path = QtWidgets.QLineEdit(self.centralwidget)
        self.camera_path.setGeometry(QtCore.QRect(50, 270, 211, 31))
        self.camera_path.setStyleSheet("font-size:15px;\n"
"font-weight:400;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);\n"
"border : none;\n"
"background-color: rgb(0, 0, 0);")
        self.camera_path.setObjectName("camera_path")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 101, 51))
        self.label_3.setStyleSheet("font-size:25px;\n"
"font-weight:1000;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.btn_finishsetting = QtWidgets.QPushButton(self.centralwidget)
        self.btn_finishsetting.setGeometry(QtCore.QRect(100, 330, 111, 41))
        self.btn_finishsetting.setStyleSheet("QPushButton{\n"
"    border-radius:10;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:16px\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:10;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font-family:微软雅黑;\n"
"    font-weight:700;\n"
"    font-size:16px\n"
"}")
        self.btn_finishsetting.setObjectName("btn_finishsetting")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 271, 381))
        self.label_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius:15px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 91, 21))
        self.label_5.setStyleSheet("font-size:16px;\n"
"font-weight:400;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.zongkedu = QtWidgets.QLineEdit(self.centralwidget)
        self.zongkedu.setGeometry(QtCore.QRect(50, 200, 211, 31))
        self.zongkedu.setStyleSheet("font-size:15px;\n"
"font-weight:400;\n"
"font-family:微软雅黑;\n"
"color: rgb(255, 255, 255);\n"
"border : none;\n"
"background-color: rgb(0, 0, 0);")
        self.zongkedu.setObjectName("zongkedu")
        self.label_4.raise_()
        self.label.raise_()
        self.fenduzhi.raise_()
        self.label_2.raise_()
        self.camera_path.raise_()
        self.label_3.raise_()
        self.btn_finishsetting.raise_()
        self.label_5.raise_()
        self.zongkedu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "表盘分度值"))
        self.label_2.setText(_translate("MainWindow", "摄像头序号或地址"))
        self.label_3.setText(_translate("MainWindow", "设置"))
        self.btn_finishsetting.setText(_translate("MainWindow", "完成设置"))
        self.label_5.setText(_translate("MainWindow", "表盘总刻度"))
